<ul>
    <li><a href="/examples/messenger/index/type/info">Info message</a></li>
    <li><a href="/examples/messenger/index/type/info-action">Info message with actions</a></li>
    
    <li><a href="/examples/messenger/index/type/success">Success message</a></li>
    <li><a href="/examples/messenger/index/type/success-action">Success message with actions</a></li>
    
    <li><a href="/examples/messenger/index/type/warning">Warning message</a></li>
    <li><a href="/examples/messenger/index/type/warning-action">Warning message with actions</a></li>
    
    <li><a href="/examples/messenger/index/type/error">Error message</a></li>
    <li><a href="/examples/messenger/index/type/error-action">Error message with actions</a></li>
    
    <li><a href="/examples/messenger/index/type/mixed">Multiple messages</a></li>
</ul>